### ISSUE TITLE
IndexError: Can't set focus, ListBox is empty

### ISSUE THREAD

**Issue by 0mp** [isamert/scli#154]
I just got the following error when I was browsing my contact list. I was using Page Up and Page Down to scroll up and down and also searching with `/`. It happened as `scli` was catching up with a lot old messages.

```
Traceback (most recent call last):
  File "/usr/local/share/scli/scli", line 4490, in <module>
    main()
  File "/usr/local/share/scli/scli", line 4484, in main
    loop.run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/local/lib/python3.8/site-packages/urwid/main_loop.py", line 233, in cb
    rval = callback(data)
  File "/usr/local/share/scli/scli", line 634, in _daemon_stdout_handler
    self._envelope_handler(envelope)
  File "/usr/local/share/scli/scli", line 653, in _envelope_handler
    self.callbacks['receive_message'](envelope)
  File "/usr/local/share/scli/scli", line 3906, in _on_receive_message
    self._on_new_message(msg)
  File "/usr/local/share/scli/scli", line 3934, in _on_new_message
    self._ui.contacts.on_new_message(msg)
  File "/usr/local/share/scli/scli", line 2316, in on_new_message
    self._move_contact_top(contact_widget)
  File "/usr/local/share/scli/scli", line 2342, in _move_contact_top
    self.focus_position = pos_new
  File "/usr/local/lib/python3.8/site-packages/urwid/listbox.py", line 547, in set_focus
    raise IndexError("Can't set focus, ListBox is empty")
IndexError: Can't set focus, ListBox is empty
```

**Comment by exquo** [comment]
Thanks for reporting! Fixed now.
