### ISSUE TITLE
Error: UntrustedIdentityException

### ISSUE THREAD

**Issue by zer0lean** [isamert/scli#155]
Hi,

I got this error:

```
Traceback (most recent call last):
  File "/usr/bin/scli", line 4663, in <module>
    main()
  File "/usr/bin/scli", line 4657, in main
    loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.9/site-packages/urwid/main_loop.py", line 233, in cb
    rval = callback(data)
  File "/usr/bin/scli", line 645, in _daemon_stdout_handler
    self._error_data_handler(error_data, envelope)
  File "/usr/bin/scli", line 694, in _error_data_handler
    if error_data['type'] == 'UntrustedIdentityException':
KeyError: 'type'
```

It happened just after I wrote a message to "Note to self" from scli and opened the conversation on the linked android app. The **UntrustedIdentity** part made me a bit unsettled, even tho it probably is nothing to worry about lol. I could replicate the issue by sending a new message to "Note to self" from scli, and when I opened the conversation on the linked android app it crashed again.

**Comment by exquo** [comment]
Should be fixed in `master` now. Thanks for letting us know!

The `UntrustedIdentityException` is indeed nothing to worry about - scli checks _whether_ this is the type of error it has received. But apparently not every signal-cli's json error even has a `type` field.
