### ISSUE TITLE
scli crash

### ISSUE THREAD

**Issue by remembertoremind** [isamert/scli#17]
I can start scli with `scli -u PHONENUMBER` and then the interface shows up and can be navigated. After about 10 seconds scli crashes with this error

```
Traceback (most recent call last):
  File "/usr/bin/scli", line 375, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/scli", line 1028, in <module>
    main()
  File "/usr/bin/scli", line 1024, in main
    loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 232, in cb
    rval = callback(data)
  File "/usr/bin/scli", line 380, in daemon_handler
    urwid.emit_signal(self, 'receive_message', 'Lost message: %r %r' % (line, e))
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 265, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3.7/site-packages/urwid/signals.py", line 295, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/bin/scli", line 831, in on_receive_message
    sender = get_envelope_contact(envelope, self.signal)
  File "/usr/bin/scli", line 140, in get_envelope_contact
    if envelope.get('target'):
AttributeError: 'str' object has no attribute 'get'
```

**Comment by isamert** [comment]
I pushed a change, it should not crash now. But there may be another problem, can you start scli with `--debug` option and send the output of `~/.local/share/scli/log`. (WARNING output may contain phone numbers/messages, please remove them before sending.)

**Comment by remembertoremind** [comment]
Thanks for the fast reply. Here is the log:

```
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
CRITICAL:root:get_contact_name:empty sender
ERROR:root:input: b'java.lang.NullPointerException'
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/scli", line 375, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Hope it helps :)

**Comment by isamert** [comment]
Are you able to send/receive messages now? Otherwise I suggest removing `~/.local/share/signal-cli` and re-linking your device. `empty sender` errors should not be real problem (it's probably related to sync issue on `signal-cli`s end, I'm also having them). I'm not sure about the last error, if re-linking does not solve your problem we can try to investigate it further.

**Comment by remembertoremind** [comment]
Weirdly enough, I created the `sclirc` and pasted `save-history=true` to keep messages. Now there is no crash.

**Comment by remembertoremind** [comment]
It seems setting the `save-history=true` keeps scli running, but crashes when I receive messages.

I'll relink, when I get home from work.

**Comment by exquo** [comment]
This must have been fixed in recent versions. Please reopen if it reappears.
