### ISSUE TITLE
Mysterious error notice: "No such file or directory: 'notify-send'"

### ISSUE THREAD

**Issue by mlncn** [isamert/scli#201]
> [Errno 2] No such file or directory: 'notify-send'
> 
> Full error traceback written to log.

Two questions:

1. Is this message from scli or signal-cli?
2. …where do i find the log?

Sorry and thanks!!

**Comment by mlncn** [comment]
Aha!  Found the log in `.local/share/scli/log`

And looks like this error has happened a lot without me noticing.

```
ERROR:root:[Errno 2] No such file or directory: 'notify-send'
Traceback (most recent call last):
  File "/home/mlncn/Applications/scli/scli/scli", line 4088, in callf
    return callf(*args, **kwargs)
  File "/home/mlncn/Applications/scli/scli/scli", line 99, in callf
    proc = subprocess.Popen(cmd, **subprocess_kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'notify-send'
```

**Comment by moppman** [comment]
It looks like you're missing `notify-send`, which is part of `libnotify`, a library for sending desktop notifications.
`notify-send` is in the [libnotify-bin package in Debian](https://packages.debian.org/bookworm/libnotify-bin).
Alternatively, you could instruct `scli` to use another notification command via flag or config file (see the code [here](https://github.com/isamert/scli/blob/master/scli#L4860)).

**Comment by mlncn** [comment]
Awesome, thank you!  Total download size for libnotify-bin 17KB :grin:
