### ISSUE TITLE
Missing .local/share/signal-cli/data/NNNNNN.d/recipients-store causes crash on startup

### ISSUE THREAD

**Issue by ppar** [isamert/scli#206]
Summary:

Using `scli` to link an existing account seems to work fine, but starting the client crashes because `~/ .local/share/signal-cli/data/NNNNNN.d/recipients-store` is missing.

Environment: 

- Debian 11 server, x86_64, no Xorg / wayland
- signal-cli installed using debian packages from https://packaging.gitlab.io/signal-cli/installation/standalone/ , version 0.11.5.1  (tried both -native and -jre)
- scli downloaded from  https://github.com/isamert/scli/releases/download/v0.7.1/scli-v0.7.1.tar.gz
- scli's dependencies installed with apt based on the old .deb package from https://gitlab.com/packaging/scli/
    ```
    Depends: python3-urwid, python3-urwid-readline, python3-pyqrcode, signal-cli-jre, dbus, python3
    ```
- dedicated UNIX user account with empty home dir

Steps to reproduce:

- Link it - seems to work fine
    ```
    myusername@myservername:~$ ./scli-v0.7.1/scli link --name myservername-071-01
    Retrieving QR code, please wait...
    ....
    Scan the QR code with Signal app on your phone and wait for the linking process to finish.
    You might need to zoom out for the QR code to display properly.
    This may take a moment...
    Receiving data for the first time...
    Done.
    ```
    
- Try to run it - crashes because something hasn't created that file
    ```
    myusername@myservername:~$ ./scli-v0.7.1/scli
    Traceback (most recent call last):
    File "/home/myusername/./scli-v0.7.1/scli", line 1029, in parse_data_file
        indivs = self._get_recipients()
    File "/home/myusername/./scli-v0.7.1/scli", line 1089, in _get_recipients
        with open(recipients_store_file, encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/myusername/.local/share/signal-cli/data/NNNNNN.d/recipients-store'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/home/myusername/./scli-v0.7.1/scli", line 5271, in <module>
        main()
    File "/home/myusername/./scli-v0.7.1/scli", line 5253, in main
        coord = Coordinate()
    File "/home/myusername/./scli-v0.7.1/scli", line 4514, in __init__
        self._contacts = Contacts(sigdata)
    File "/home/myusername/./scli-v0.7.1/scli", line 1219, in __init__
        self.reload()
    File "/home/myusername/./scli-v0.7.1/scli", line 1222, in reload
        indivs_dicts, groups_dicts = self.sigdata.parse_data_file()
    File "/home/myusername/./scli-v0.7.1/scli", line 1031, in parse_data_file
        indivs = self._get_recipients_v1()
    File "/home/myusername/./scli-v0.7.1/scli", line 1126, in _get_recipients_v1
        for cont in self._data['contactStore']['contacts']:
    KeyError: 'contactStore'
    ```

- Files that were created under .local:
    ```
    myusername@myservername:~$ find .local -ls
    264613      4 drwxr-xr-x   3 myusername   myusername       4096 joulu 14 03:13 .local
    264614      4 drwxr-xr-x   4 myusername   myusername       4096 joulu 14 03:13 .local/share
    264615      4 drwxr-xr-x   3 myusername   myusername       4096 joulu 14 03:13 .local/share/scli
    264616      4 drwxr-xr-x   2 myusername   myusername       4096 joulu 14 03:13 .local/share/scli/attachments
    268762      4 drwx------   3 myusername   myusername       4096 joulu 14 03:13 .local/share/signal-cli
    268763      4 drwx------   3 myusername   myusername       4096 joulu 14 03:13 .local/share/signal-cli/data
    268766      4 drwx------   2 myusername   myusername       4096 joulu 14 03:15 .local/share/signal-cli/data/NNNNNN.d
    268767    156 -rw-r--r--   1 myusername   myusername     159744 joulu 14 03:14 .local/share/signal-cli/data/NNNNNN.d/account.db
    268765      4 -rw-------   1 myusername   myusername       1140 joulu 14 03:14 .local/share/signal-cli/data/NNNNNN
    268764      4 -rw-------   1 myusername   myusername        180 joulu 14 03:13 .local/share/signal-cli/data/accounts.json
    ```

Tests as per README.md:

- Testing "receive" - either shows nothing, or a bunch of sync messages confirming the account was linked successfully

    ```
    myusername@myservername:~$ signal-cli -u +MYPHONENR receive
    ....
    Envelope from: “MYNAME” +MYPHONENR (device: 1) to +MYPHONENR
    Timestamp: 1670985873616 (2022-12-14T02:44:33.616Z)
    Server timestamps: received: 1670985874175 (2022-12-14T02:44:34.175Z) delivered: 1670986060362 (2022-12-14T02:47:40.362Z)
    Received a sync message
    ....
    ```

- Testing "daemon" fails because DISPLAY is not set. This is a server machine, so no X11 or friends. Is this test actually relevant for scli? AFAIK it executes signal-cli in a subprocess and I guess talks to it over stdout/stdin, does it need a dbus daemon running somewhere?
    ```
    myusername@myservername:~$ signal-cli -u +MYPHONENR daemon
    INFO  DaemonCommand - Starting daemon in single-account mode for +MYPHONENR
    org.freedesktop.dbus.exceptions.AddressResolvingException: Cannot Resolve Session Bus Address: DISPLAY variable not set
            at org.freedesktop.dbus.utils.AddressBuilder.getSessionConnection(AddressBuilder.java:64)
            at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forSessionBus(DBusConnectionBuilder.java:42)
            at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forType(DBusConnectionBuilder.java:89)
            at org.freedesktop.dbus.connections.impl.DBusConnectionBuilder.forType(DBusConnectionBuilder.java:76)
            at org.asamk.signal.commands.DaemonCommand.runDbus(DaemonCommand.java:385)
            at org.asamk.signal.commands.DaemonCommand.runDbusSingleAccount(DaemonCommand.java:327)
            at org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:158)
            at org.asamk.signal.App.handleLocalCommand(App.java:289)
            at org.asamk.signal.App.init(App.java:229)
            at org.asamk.signal.Main.main(Main.java:60)
    ```

**Comment by exquo** [comment]
The missing `recipients-store` issue is #202. It has been fixed in `master`, but the releases had not been updated, till now. I have made a new release that catches up with it. Try using [`v0.7.2`](https://github.com/isamert/scli/releases/tag/v0.7.2), or just clone this repo with `git`.

**Comment by exquo** [comment]
> Testing "daemon" fails because DISPLAY is not set. This is a server machine, so no X11 or friends. 

Scli listens to signal-cli's daemon's stdout, but sends commands to its dbus service (see also my reply in #207). 

These were the choices available at the time scli has been written. Now that signal-cli offers JSON-RPC over stdin/out that would have been preferred, and would remove the dbus dependency.

X11 or a desktop environment is not required for scli, as long as the DBUS session is running. But dbus might fail to start if the `$DISPLAY` variable is not set, as in #200 or AsamK/signal-cli#1070. There are several questions on stackoverflow etc about this (I have tried googling "dbus display not set"). One way around this seems to be: execute `export DBUS_SESSION_BUS_ADDRESS=""`. DBus docs on this: https://dbus.freedesktop.org/doc/dbus-launch.1.html. Maybe also helpful: https://github.com/AsamK/signal-cli/wiki/DBus-service#macos-and-dbus-send.
