### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by joao456** [isamert/scli#27]
With signal-cli already installed and running and device already linked:

```
$ sudo apt update && sudo apt install libunixsocket-java python3-urwid
$ git clone https://github.com/isamert/scli.git && cd scli
$ signal-cli -u PHONE_NUMBER updateAccount
$ signal-cli -u PHONE_NUMBER receive
```

When running:
`$ ./scli  -u PHONE_NUMBER`

I get:
```

Traceback (most recent call last):
  File "./scli", line 1519, in <module>
    main()
  File "./scli", line 1503, in main
    window = MainWindow(state)
  File "./scli", line 1019, in __init__
    self._wchat = ChatWindow(self.state)
  File "./scli", line 839, in __init__
    urwid.connect_signal(self._wline, 'postchange', self.on_edit_text_changed)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 154, in connect
    (name, obj))
NameError: No such signal 'postchange' for object <Edit selectable flow widget '' caption='> ' edit_pos=0>
```

**Comment by isamert** [comment]
Probably the `python3-urwid` package is outdated in your system. Can you send the output of following code:
```sh
python -c "import urwid; print(urwid.version.VERSION)"
```

If it's lower than `(2, 0, 1)`, I recommend you to install urwid using `pip`. I'm not sure about the package names in your distro but:
```sh
sudo apt remove python3-urwid # Remove the outdated one
sudo apt install python3-pip # install pip
sudo pip3 install urwid 
# OR if you don't want a system wide installation, just use this instead of the last command
# I also recommend installing this way: 
pip3 install --user urwid # Don't use sudo here
```

**Comment by isamert** [comment]
Assuming it's resolved. Feel free to re-open if the issue persists.
