### ISSUE TITLE
Unable to receive or send messages on macOS

### ISSUE THREAD

**Issue by binarious** [isamert/scli#28]
I am unable to receive or send messages on macOS.

**Steps to reproduce**
- `brew install signal-cli`
- `pip3 install urwid`
- `signal-cli link -n "MYNAME"` + Scan on phone
- `signal-cli -u MYPHONE receive`
- Run `scli` and send a message. The sender doesn't receive it.
- `signal-cli -u USERNAME send -m "This is a message" RECEIVER` does work though

**System details**
- macOS: 10.14.5
- signal-cli: 0.6.2
- Python: 3.7.3
- scli: https://github.com/isamert/scli/commit/0dfafc87995f79ee7ee59f05e6d7064720a04352

**Debug log**
```
ERROR:root:input: b'org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address'
ERROR:root:Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR:root:input: b'\tat org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:246)'
ERROR:root:Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "./scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
ERROR:root:input: b'\tat org.asamk.signal.commands.DaemonCommand.handleCommand(DaemonCommand.java:49)'
ERROR:root:Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "./scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
ERROR:root:input: b'\tat org.asamk.signal.Main.handleCommands(Main.java:115)'
ERROR:root:Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "./scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
ERROR:root:input: b'\tat org.asamk.signal.Main.main(Main.java:50)'
ERROR:root:Expecting value: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "./scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
ERROR:root:send_message: exit code=3:err=b'org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address\n\tat org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:246)\n\tat org.asamk.signal.Main.handleCommands(Main.java:69)\n\tat org.asamk.signal.Main.main(Main.java:50)\n'
ERROR:root:send_message: exit code=3:err=b'org.freedesktop.dbus.exceptions.DBusException: Cannot Resolve Session Bus Address\n\tat org.freedesktop.dbus.DBusConnection.getConnection(DBusConnection.java:246)\n\tat org.asamk.signal.Main.handleCommands(Main.java:69)\n\tat org.asamk.signal.Main.main(Main.java:50)\n'
```

**Comment by binarious** [comment]
Seems to be an issue with signal-cli: https://github.com/AsamK/signal-cli/issues/145
