### ISSUE TITLE
No such signal 'postchange' for object

### ISSUE THREAD

**Issue by aaronjanse** [isamert/scli#29]
```
Traceback (most recent call last):
  File "scli", line 1519, in <module>
    main()
  File "scli", line 1503, in main
    window = MainWindow(state)
  File "scli", line 1019, in __init__
    self._wchat = ChatWindow(self.state)
  File "scli", line 839, in __init__
    urwid.connect_signal(self._wline, 'postchange', self.on_edit_text_changed)
  File "/nix/store/0rblzp15vqlbmnq6f8iadlkrwj3sghcd-python3.7-urwid-1.3.1/lib/python3.7/site-packages/urwid/signals.py", line 154, in connect
    (name, obj))
NameError: No such signal 'postchange' for object <Edit selectable flow widget '' caption='> ' edit_pos=0>
```

---

Thanks for writing `scli`! I'd be happy to provide further info to help debug

**Comment by isamert** [comment]
Can you try what is said in #27 and report back?

**Comment by isamert** [comment]
Assuming it's resolved, closing. Feel free to re-open if the issue persists.
