### ISSUE TITLE
Not receiving replies

### ISSUE THREAD

**Issue by felleg** [isamert/scli#31]
Hi! I'm looking forward to try out this application, but so far all I was able to do is send messages, not receive them.

Here is what I did, in order:
1. I'm running Ubuntu 16.04 LTS
1. I have Signal Android installed on my phone, where my account is registered
1. I have installed signal-cli 0.6.3, installed using the `Install system-wide on Linux` instructions from the signal-cli README
1. I have cloned the scli repository on my computer
1. `signal-cli link -n "mypc"`, copy the link shown on screen, and I leave this process running.
1. In another tab, I run `qrencode 'LINK' -o qrcode.png`
1. I open the "Linked Devices" settings on the Android app and scan the content of `qrcode.png`
1. `signal-cli -u +xxxxxxxxxxx receive`, with x being my phone number.
1. I launch `scli`.

I see my contacts and groups. I'm able to send messages to them (I see my own messages pop up on my phone). However, when they reply to me, the answer does not show up in scli, as if they never responded.

I tried to register my phone number directly on my computer to see if it makes any difference, but the result is the same.

I'm afraid I cannot do much more at the moment, since I reached the maximum number of registrations per day for my phone number. Any suggestion? I'm very surprised to have this issue, since everyone else seems to be enjoying the app just fine.

**Comment by felleg** [comment]
EDIT:
I have opened the scli app in debug mode and looked at the log. I noticed that this error happens every time I send a message:

```
ERROR:root:input: b'{"envelope":{"source":"+1[REDACTED]","sourceDevice":2,"relay":null,"timestamp":1570715659083,"isReceipt":true,"dataMessage":null,"syncMessage":null,"callMessage":null}}'
ERROR:root:the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/legerf/scli/scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
ERROR:root:input: b'{"envelope":{"source":"+1[REDACTED]","sourceDevice":1,"relay":null,"timestamp":1570715659083,"isReceipt":true,"dataMessage":null,"syncMessage":null,"callMessage":null}}'
ERROR:root:the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/legerf/scli/scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
Also, I noticed when a contact replied to me, the message did not appear, but the log did receive the message with an error:

```
ERROR:root:input: b'{"envelope":{"source":"+1[REDACTED]","sourceDevice":2,"relay":null,"timestamp":1570715803978,"isReceipt":false,"dataMessage":{"timestamp":1570715803978,"message":"THIS IS A MESSAGE","expiresInSeconds":0,"attachments":[],"groupInfo":null},"syncMessage":null,"callMessage":null}}'
ERROR:root:the JSON object must be str, not 'bytes'
Traceback (most recent call last):
  File "/home/legerf/scli/scli", line 612, in daemon_handler
    e = json.loads(line)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
Seems like a similar error in both cases. Turns out that modifying line 612 in `scli` to add a `decode('utf-8')` did the trick for me. I will create a pull request.
